defaults: &defaults
  dirs:
    # files are taken from this directory
    inbox: '/var/webapps/kamyshko/current/inbox'
    # processed files are moved here
    backup: '/var/webapps/kamyshko/current/inbox/backup'
    faults:
      # files for which there were no couples (pdf without txt, txt without pdf)
      orphans: '/var/webapps/kamyshko/current/inbox/faults/orphans'
      # file name does not match the standard
      badnamed: '/var/webapps/kamyshko/current/inbox/faults/badnamed'
      # this issue is already in db
      duplicates: '/var/webapps/kamyshko/current/inbox/faults/duplicates'
      # error while saving issue in db
      refused: '/var/webapps/kamyshko/current/inbox/faults/refused'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
