defaults: &defaults
  dirs:
    # отсюда берутся файлы:
    inbox: '/var/webapps/kamyshko/inbox'
    # сюда перемещаются обработанные файлы:
    backup: '/var/webapps/kamyshko/inbox/backup'
    faults:
      # файлы, для которых не нашлось пары (pdf без txt, txt без pdf)
      orphans: '/var/webapps/kamyshko/inbox/faults/orphans'
      # имя файла не соответствует стандарту
      badnamed: '/var/webapps/kamyshko/inbox/faults/badnamed'
      # этот выпуск уже есть в базе
      duplicates: '/var/webapps/kamyshko/inbox/faults/duplicates'
      # ошибка во время сохранения выпуска в базе
      refused: '/var/webapps/kamyshko/inbox/faults/refused'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
