# russian magazines
- ["5 колесо", "http://www.5koleso.ru/"]
- ["7 Дней", "http://7dn.ru/"]
- ["9 месяцев", "http://www.9months.ru/"]
- ["AD/Architectural Digest"]
- ["AirUnion"]
- ["Autonews"]
- ["BYTE/Россия", "http://www.bytemag.ru/"]
- ["Beauty"]
- ["Bravo International"]
- ["C-News", "http://www.cnews.ru/"]
- ["CIO"]
- ["CIO.RU Директор"]
- ["CRN/ИТ-бизнес (Сomputer reseller news)"]
- ["Chip"]
- ["Cigar clan", "http://www.cigarclan.ru/"]
- ["Commercial Real Estate"]
- ["CompuTerra", "http://www.computerra.ru/"]
- ["Computer Bild"]
- ["Computer World Россия", "http://www.osp.ru/cw/"]
- ["Connect! Мир связи", "http://www.connect.ru/"]
- ["Cosmopolitan"]
- ["Cosmopolitan Beauty", "http://www.cosmobeauty.ru/"]
- ["Cosmopolitan Shoping", "http://www.cosmoshopping.ru/"]
- ["DVD Эксперт"]
- ["Digital Camera Photo&Video"]
- ["Digital Photo", "http://www.digital-photo.ru/"]
- ["Digital magazine"]
- ["Doctor Travel/Доктор Тревел"]
- ["Elle"]
- ["Elle Girl"]
- ["Elle Декор"]
- ["Empire"]
- ["Esquire"]
- ["FHM"]
- ["Fashion Collection"]
- ["Forbes (русская версия)", "http://www.axelspringer.ru/editions/forbes/"]
- ["Forbes Style"]
- ["GEO", "http://www.geo.ru/"]
- ["GEO Traveller"]
- ["GQ Gentlemen's Quarterly"]
- ["Glamour"]
- ["Grazia"]
- ["HELLO!"]
- ["HR magazine"]
- ["Hard'n'Soft", "http://www.hardnsoft.ru/"]
- ["Harper's Bazaar", "http://www.bazaar.ru/"]
- ["Harvard Business Review"]
- ["IT Manager"]
- ["IT News"]
- ["IXBT.COM"]
- ["In Style"]
- ["Inflight review"]
- ["Intelligent Enterprise"]
- ["JOY"]
- ["L'officiel"]
- ["LAN"]
- ["Magnum"]
- ["Make UP"]
- ["Marie Claire", "http://www.marieclaire.ru/"]
- ["Maxim"]
- ["Men's Health", "http://www.mhealth.ru/"]
- ["Menu magazine"]
- ["Mini. Бурда", "http://www.burda.ru/Magazine/Mini.aspx"]
- ["Mobi"]
- ["Mobile magazine"]
- ["Mobile news Review"]
- ["National Geographic Traveler"]
- ["National Geographic Россия"]
- ["Natural Health. Здоровье от природы"]
- ["OK!", "http://www.axelspringer.ru/editions/ok_magazine/"]
- ["Onboard"]
- ["Oops!"]
- ["Outdoormedia", "http://www.outdoormedia.ru/"]
- ["PC Magazine", "http://www.pcmag.ru/"]
- ["PC Mobile"]
- ["PC Week", "http://www.pcweek.ru/numbers/"]
- ["Parents - Счастливые родители"]
- ["Playboy", "http://www.playboy.com.ru/"]
- ["Pro Спорт", "http://www.prosportmagazine.ru/"]
- ["Psychologies. Психология"]
- ["Quatroroute"]
- ["Robb Report"]
- ["Rolling Stone"]
- ["SYNC"]
- ["Sales business/Продажи"]
- ["Seasons"]
- ["Sex & the City"]
- ["Shape"]
- ["Shape-мама"]
- ["Simple Wine news", "http://www.simplewinenews.ru/"]
- ["Sport week", "http://sportweek.ru/"]
- ["Starhit"]
- ["Stereo & Video"]
- ["Stuff"]
- ["TTG"]
- ["Tatler"]
- ["Techno News"]
- ["Time Out Москва", "http://www.timeout.ru/"]
- ["Tobacco Ревю", "http://www.tobaccoreview.com/"]
- ["Top gear"]
- ["Total DVD", "http://www.totaldvd.ru/"]
- ["Upgrade"]
- ["Upgrade Special"]
- ["VIM Avia"]
- ["Viva!"]
- ["Vogue"]
- ["Votre Beaute"]
- ["What Hi Fi"]
- ["What car"]
- ["XXL"]
- ["Yes!"]
- ["Yes!-Звезды"]
- ["hecho amano", "http://www.hechoamano.ru/"]
- ["iVan"]
- ["Авто (из рук в руки)"]
- ["Автогид"]
- ["Автозвук"]
- ["Автоизвестия", "http://www.autoizvestia.ru/"]
- ["Автомагазин"]
- ["Автомир"]
- ["Автомобили"]
- ["Автомобили и цены"]
- ["Автопанорама"]
- ["Авторевю"]
- ["Автоспорт"]
- ["АиФ Про Здоровье"]
- ["Аистенок"]
- ["Антенна-Телесемь", "http://www.antenna-telesem.ru/"]
- ["Архидом", "http://www.archidom.ru/archidom.html"]
- ["Атмосфера"]
- ["АудиоМагазин"]
- ["Афиша"]
- ["Афиша-Мир"]
- ["Аэрофлот"]
- ["Банки и деловой мир"]
- ["Банковские технологии"]
- ["Банковское обозрение", "http://bo.bdc.ru/"]
- ["Белый бизнес"]
- ["Беременность. Мама и малыш"]
- ["Бизнес и банки"]
- ["Бизнес-журнал"]
- ["Большой бизнес"]
- ["Бурда/Burda"]
- ["Бюджет"]
- ["Ваш досуг", "http://www.vashdosug.ru/"]
- ["Вестник связи"]
- ["Винная карта"]
- ["Витрина. Мир супермаркета"]
- ["Вкусно и полезно"]
- ["Вокруг света", "http://www.vokrugsveta.ru/"]
- ["Вояж и отдых"]
- ["Все для женщины"]
- ["Высокий полет"]
- ["Гастрономъ"]
- ["Горные лыжи (SKI)"]
- ["Деловой мир. Туризм и отдых"]
- ["Директор информационной службы"]
- ["Дом и интерьер"]
- ["Домашний очаг"]
- ["Домовой"]
- ["Домодедово"]
- ["Железо"]
- ["Женские секреты мини"]
- ["Жизнь"]
- ["За рубежом", "http://www.zarubejom.com/"]
- ["За рулем", "http://www.zr.ru/"]
- ["Здоровье"]
- ["Здоровье от природы"]
- ["Игромания"]
- ["Идеи вашего дома", "http://www.ivd.ru/"]
- ["Империя Вкуса"]
- ["Интерьер + дизайн"]
- ["Интерьер 100%Office"]
- ["Интерьер Дайджест"]
- ["ИнформКурьер-СВЯЗЬ"]
- ["КДО Информ (Квартира. Дача. Офис)"]
- ["Кадровое дело", "http://www.kdelo.ru/"]
- ["Караван историй", "http://www.karavan.ru/"]
- ["Карьера"]
- ["Квартирный ряд"]
- ["Кино Парк", "http://old.film.ru/kp/"]
- ["Кинобизнес сегодня", "http://www.kinobusiness.com/"]
- ["Клаксон"]
- ["Клуб 4х4"]
- ["КоммерсантЪ - Телеком"]
- ["Коммерческий транспорт"]
- ["Компьютер Пресс", "http://www.compress.ru/"]
- ["Красивые дома"]
- ["Красивые дома (бассейны и сауны)"]
- ["Красивые квартиры"]
- ["Красота и здоровье"]
- ["Крестьянка", "http://www.krestyanka.ru/"]
- ["Купи авто/Выбор за Вами"]
- ["Лиза"]
- ["Лиза. Girl"]
- ["Лиза. Гороскоп"]
- ["Лиза. Добрые советы"]
- ["Лиза. Мой ребенок"]
- ["Лиза. Мой уютный дом", "http://www.burda.ru/Magazine/MoyDom.aspx"]
- ["Лица"]
- ["Личный Бюджет"]
- ["Лучшие интерьеры"]
- ["Лучшие цифровые камеры"]
- ["МК мобиль", "http://www.mk.ru/mobil/"]
- ["МК-Бульвар"]
- ["Магия Cosmo", "http://www.cosmo-magia.ru/"]
- ["Маркетинг PRO"]
- ["Медведь"]
- ["Мезонин"]
- ["Мир ПК"]
- ["Мир ТВ и кино"]
- ["Мир новостей", "http://www.mirnov.ru/"]
- ["Мир&Дом.City"]
- ["Мир&Дом.Residence"]
- ["Мир&Дом.Элитная недвижимость"]
- ["Мобильные компьютеры"]
- ["Мое дело. Магазин"]
- ["Мое дело. Ресторан"]
- ["Мой кроха и я"]
- ["Мой маленький"]
- ["Мой ребенок. Мамочкина школа", "http://www.burda.ru/Magazine/MamShkola.aspx"]
- ["Молл"]
- ["Национальный банковский журнал", "http://www.nbj.ru/"]
- ["Недвижимость & цены", "http://d-mir.ru/journal/nic/"]
- ["Новости авторемонта"]
- ["Новости торговли", "http://www.nta-rus.com/publishing/news_trade/"]
- ["Новый адрес"]
- ["Няня"]
- ["Оборудование: рынок, предложение, цены (прилож. к журналу \"Эксперт\")"]
- ["Обучение и карьера"]
- ["Отдохни!"]
- ["Отдохни! Имена"]
- ["Открытые системы. СУБД"]
- ["Паппарацци"]
- ["Под градусом"]
- ["Покупаем от А до Я"]
- ["Полный привод 4х4"]
- ["Популярная механика", "http://www.popmech.ru/"]
- ["Потребитель. Экспертиза и тесты"]
- ["Про кино"]
- ["Промышленный еженедельник", "http://www.promweekly.ru/"]
- ["Прямые инВЕСТИции"]
- ["РБК"]
- ["Рекламные идеи"]
- ["Ресторанные ведомости", "http://www.restoved.ru/"]
- ["Ресторатор"]
- ["Российская торговля (журнал)"]
- ["Русский репортер", "http://www.rusrep.ru/"]
- ["Салон Audio&Video"]
- ["Салон Интерьер"]
- ["Салон красоты"]
- ["СамаЯ. Мама, это Я!"]
- ["Самая"]
- ["Свой бизнес"]
- ["Секрет фирмы", "http://www.kommersant.ru/sf/"]
- ["Сети/Network World"]
- ["Собака МСК"]
- ["Советник"]
- ["Современный дом"]
- ["Спрос"]
- ["Стандарт"]
- ["Стильные прически"]
- ["Строительная газета", "http://www.stroygaz.ru/"]
- ["Строительный эксперт"]
- ["Сударушка", "http://www.sudarushka.su/"]
- ["ТВ-Парк"]
- ["ТВ7", "http://www.tv7.ru/"]
- ["Тара и упаковка"]
- ["Теленеделя", "http://teleweek.ru/"]
- ["Телепрограмма"]
- ["Техника для бизнеса"]
- ["Техника третьего тысячелетия"]
- ["Техногид", "http://www.tehnogid.ru/"]
- ["Технологии и средства связи"]
- ["Торговая газета", "http://www.t-gazeta.ru/"]
- ["Турбизнес"]
- ["Туринфо"]
- ["Управление персоналом"]
- ["Фармацевтический вестник", "http://www.pharmvestnik.ru/"]
- ["Фильм"]
- ["Финнансовый директор"]
- ["Фото & видео"]
- ["Фотодело"]
- ["Фотомастерская"]
- ["Хакер"]
- ["Худеем правильно"]
- ["Хулиган"]
- ["Что нового в науке и технике"]
- ["Шеф.(Ресторатор)."]
- ["Штучка"]
- ["Эгоист generation", "http://www.egoist-generation.ru/"]
- ["Эксперт"]
- ["Экспресс-электроника (IT Expert)"]
- ["Электросвязь"]
- ["Энотека"]
- ["Эстетика"]
- ["оТВеть!"]
